server:
  port: 8084
  servlet:
    context-path: /

spring:
  datasource:

    username: root
    password: toor
    url: jdbc:h2:file:./db/sample_db
    driver-class-name: org.h2.Driver



jwt:
  token:
    secret: muchsecretwow
    expired: 3600000

rest-api:
  url: /api/v1
  auth-url: /api/v1/auth
  admin-url: /api/v1/admin
  protected-url: /api/v1/protected
